# Generated by Django 3.2 on 2022-11-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionandhint',
            name='activityid',
        ),
        migrations.AddField(
            model_name='questionandhint',
            name='keynameactivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.activity', to_field='keyname'),
        ),
    ]
